-- ================================================================
-- AIR TRACKER DATABASE SCHEMA
-- ================================================================
--
-- Airport configuration:
--   API input  -> ICAO
--   Database   -> IATA for flight relationships
--
-- Example:
--   VIDP -> DEL
--   VOBL -> BLR
--   KATL -> ATL
--
-- Existing data is normally preserved because db_manager.py
-- does NOT use force_recreate=True.
--
-- IMPORTANT:
-- Running this file manually will DROP the tables below.
-- ================================================================


-- ================================================================
-- DROP TABLES
-- ================================================================

DROP TABLE IF EXISTS fetched_windows;
DROP TABLE IF EXISTS airport_delays;
DROP TABLE IF EXISTS flights;
DROP TABLE IF EXISTS aircraft;
DROP TABLE IF EXISTS airport;


-- ================================================================
-- AIRPORT
-- ================================================================

CREATE TABLE airport (

    airport_id INT AUTO_INCREMENT PRIMARY KEY,

    -- ICAO identifier used by AeroDataBox
    icao_code VARCHAR(10) UNIQUE,

    -- IATA identifier used by the flights/delays tables
    iata_code VARCHAR(10) UNIQUE NOT NULL,

    name VARCHAR(255),

    city VARCHAR(100),

    country VARCHAR(100),

    continent VARCHAR(100),

    latitude DECIMAL(10,7),

    longitude DECIMAL(10,7),

    timezone VARCHAR(100)

);


-- ================================================================
-- AIRCRAFT
-- ================================================================

CREATE TABLE aircraft (

    aircraft_id INT AUTO_INCREMENT PRIMARY KEY,

    registration VARCHAR(50) UNIQUE NOT NULL,

    model VARCHAR(100),

    manufacturer VARCHAR(100),

    icao_type_code VARCHAR(20),

    owner VARCHAR(255)

);


-- ================================================================
-- FLIGHTS
-- ================================================================

CREATE TABLE flights (

    -- Generated by extract_data.py.
    --
    -- Example:
    --   EK123_2026-08-15 08:30:00
    --
    -- This prevents flights with the same flight number
    -- on the same date from incorrectly overwriting each other.

    flight_id VARCHAR(150) PRIMARY KEY,

    flight_number VARCHAR(50),

    aircraft_registration VARCHAR(50),

    -- These are IATA codes.
    origin_iata VARCHAR(10),

    destination_iata VARCHAR(10),

    scheduled_departure DATETIME NULL,

    actual_departure DATETIME NULL,

    scheduled_arrival DATETIME NULL,

    actual_arrival DATETIME NULL,

    status VARCHAR(50),

    airline_code VARCHAR(20)

);


-- ================================================================
-- AIRPORT DELAY STATISTICS
-- ================================================================

CREATE TABLE airport_delays (

    delay_id INT AUTO_INCREMENT PRIMARY KEY,

    -- Must correspond to airport.iata_code
    airport_iata VARCHAR(10) NOT NULL,

    delay_date DATE NOT NULL,

    total_flights INT DEFAULT 0,

    delayed_flights INT DEFAULT 0,

    avg_delay_min DECIMAL(10,2) NULL,

    median_delay_min DECIMAL(10,2) NULL,

    canceled_flights INT DEFAULT 0,

    -- One row per airport per date.
    UNIQUE KEY uniq_airport_delay_date (
        airport_iata,
        delay_date
    ),

    CONSTRAINT fk_delay_airport
        FOREIGN KEY (airport_iata)
        REFERENCES airport(iata_code)
        ON DELETE CASCADE
        ON UPDATE CASCADE

);


-- ================================================================
-- FETCHED API WINDOWS
-- ================================================================
--
-- This table makes flight extraction resumable.
--
-- Example:
--
--   airport = KATL
--   window   = 2026-08-15T00:00 -> 2026-08-15T12:00
--
-- Once successfully processed, the window is recorded here.
--
-- If the API returns an error or HTTP 429, extract_data.py does
-- NOT insert the window, so the next run can retry it.
-- ================================================================

CREATE TABLE fetched_windows (

    id INT AUTO_INCREMENT PRIMARY KEY,

    -- Despite the variable name in the Python code,
    -- this value is the monitored airport code supplied to the
    -- extraction layer (currently ICAO, e.g. KATL).
    airport_iata VARCHAR(10) NOT NULL,

    window_start VARCHAR(20) NOT NULL,

    window_end VARCHAR(20) NOT NULL,

    UNIQUE KEY uniq_window (
        airport_iata,
        window_start,
        window_end
    )

);


-- ================================================================
-- FLIGHT INDEXES
-- ================================================================

CREATE INDEX idx_flights_origin
    ON flights(origin_iata);


CREATE INDEX idx_flights_destination
    ON flights(destination_iata);


CREATE INDEX idx_flights_status
    ON flights(status);


CREATE INDEX idx_flights_aircraft
    ON flights(aircraft_registration);


CREATE INDEX idx_flights_scheduled_departure
    ON flights(scheduled_departure);


CREATE INDEX idx_flights_scheduled_arrival
    ON flights(scheduled_arrival);


CREATE INDEX idx_flights_airline
    ON flights(airline_code);


-- ================================================================
-- AIRCRAFT INDEX
-- ================================================================

CREATE INDEX idx_aircraft_model
    ON aircraft(model);


-- ================================================================
-- AIRPORT INDEXES
-- ================================================================

CREATE INDEX idx_airport_country
    ON airport(country);


CREATE INDEX idx_airport_city
    ON airport(city);


-- ================================================================
-- DELAY INDEX
-- ================================================================

CREATE INDEX idx_delay_airport_date
    ON airport_delays(
        airport_iata,
        delay_date
    );


-- ================================================================
-- FETCHED WINDOW INDEX
-- ================================================================

CREATE INDEX idx_fetched_windows_airport
    ON fetched_windows(airport_iata);


-- ================================================================
-- END OF SCHEMA
-- ================================================================